### PR TITLE
fixing bug on tokens not being counted

### LINKED ISSUE #47: [BUG] HourlyTotals entity has non sense results.
Run this query:
```
{
	hourlyTotals(where:{totalTokens: 0},
        first: 200) {
        volumeUsd
	    timestamp
        numberOfTrades
        tokens{
            symbol
        }
        totalTokens
	}
}
```
There will be values returned that contains` []` tokens and `0` totalTokens but there's a value in the total volume and there are also trades.

### PR DESCRIPTION
**Pull request by GabrielCamba**
token was counted only on creation or adding firstTradeTimestamp. counting was extracted to fix the issue. 

closes #47

### CODE REVIEW

**Review by alfetopito — COMMENTED** [review]
Is this change still needed after what was discussed yesterday?
I mean the need to count the tokens traded in 1h or 24h periods

**Comment by GabrielCamba** [comment]
> Is this change still needed after what was discussed yesterday? I mean the need to count the tokens traded in 1h or 24h periods

I think is not needed. Already talked with the team and we will comment the properties code of  tokens and total tokens in daily and hourly totals entities.

**Comment by GabrielCamba** [comment]
To avoid complexity we decided to comment the props and all the logic behind them. The code will keep there commented for being used if needed. We will need to add a set for tokens property (checking we don't add dups) and totalTokens should keep the size of those tokens property.

**Comment by GabrielCamba** [comment]
Already deployed and indexing here: https://thegraph.com/hosted-service/subgraph/gabrielcamba/cow-one

**Review by alfetopito — APPROVED** [review]

**Pull request merged**
