### PR TITLE
Simplify deploying to your test subgraph

### PR DESCRIPTION
**Pull request by anxolin**
This PR allows to setup in your local config your test subgraph.

This way, you can deploy there in a simple way.
The README has been updated accordinly.

image

### CODE REVIEW

**Review by GabrielCamba — COMMENTED** [review]
:+1:

**Comment by anxolin** [comment]
@GabrielCamba i guess your thumbsup is an approve. Please, select approve instead of comment if u are really approving. In principle i should merge only if this is green:
image

**Review by GabrielCamba — APPROVED** [review]
:+1:

**Comment by anxolin** [comment]
Much better :)

**Pull request merged**
